# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ok_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_info = QtWidgets.QGroupBox(Dialog)
        self.group_info.setObjectName("group_info")
        self.formLayout = QtWidgets.QFormLayout(self.group_info)
        self.formLayout.setObjectName("formLayout")
        self.info_label = QtWidgets.QLabel(self.group_info)
        self.info_label.setObjectName("info_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.info_label)
        self.verticalLayout.addWidget(self.group_info)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.group_info.setTitle(_translate("Dialog", "Info"))
        self.info_label.setText(_translate("Dialog", "This app was created by Kirill Kostenko\nBackround picture was taken from https://wallpaperaccess.com/raspberry-pi\n"
"Use at your own risk\n"
"March 2021"))
